In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [13]:
inputs = df.drop('salary_more_then_100k',axis = 'columns')
target = df['salary_more_then_100k'] 

In [15]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [20]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_company.fit_transform(inputs['job'])
inputs['degree_n'] = le_company.fit_transform(inputs['degree'])

inputs

company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [25]:
inputs_n = inputs.drop(['company','job','degree'],axis= 'columns')
inputs_n

company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [27]:
from sklearn import tree

In [28]:
model = tree.DecisionTreeClassifier()

In [30]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [32]:
model.score(inputs_n,target)

1.0

In [34]:
model.predict([[2,2,1]])

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [36]:
model.predict([[2,0,1]])

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [1]:
import pandas as pd
import numpy as np

In [52]:
df = pd.read_csv("titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [31]:
inputs = df[['Pclass','Sex','Age','Fare',]]
mn = inputs['Age'].mean()

In [54]:
target = df['Survived']
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [38]:
inputs['Age'].fillna(mn,inplace =True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_8964\3384590326.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inputs['Age'].fillna(mn,inplace =True)


In [41]:
inputs

Pclass     Sex        Age     Fare
0         3    male  22.000000   7.2500
1         1  female  38.000000  71.2833
2         3  female  26.000000   7.9250
3         1  female  35.000000  53.1000
4         3    male  35.000000   8.0500
..      ...     ...        ...      ...
886       2    male  27.000000  13.0000
887       1  female  19.000000  30.0000
888       3  female  29.699118  23.4500
889       1    male  26.000000  30.0000
890       3    male  32.000000   7.7500

[891 rows x 4 columns]

In [57]:
from sklearn.preprocessing import LabelEncoder

In [59]:
le_Sex = LabelEncoder()

In [66]:
inputs['le_Sex'] = le_Sex.fit_transform(inputs['Sex'])
inputs

Pclass     Sex        Age     Fare  le_Sex
0         3    male  22.000000   7.2500       1
1         1  female  38.000000  71.2833       0
2         3  female  26.000000   7.9250       0
3         1  female  35.000000  53.1000       0
4         3    male  35.000000   8.0500       1
..      ...     ...        ...      ...     ...
886       2    male  27.000000  13.0000       1
887       1  female  19.000000  30.0000       0
888       3  female  29.699118  23.4500       0
889       1    male  26.000000  30.0000       1
890       3    male  32.000000   7.7500       1

[891 rows x 5 columns]

In [70]:
finputs = inputs.drop(['Sex'],axis = 'columns')
finputs

Pclass        Age     Fare  le_Sex
0         3  22.000000   7.2500       1
1         1  38.000000  71.2833       0
2         3  26.000000   7.9250       0
3         1  35.000000  53.1000       0
4         3  35.000000   8.0500       1
..      ...        ...      ...     ...
886       2  27.000000  13.0000       1
887       1  19.000000  30.0000       0
888       3  29.699118  23.4500       0
889       1  26.000000  30.0000       1
890       3  32.000000   7.7500       1

[891 rows x 4 columns]

In [75]:
from sklearn import tree

In [77]:
model = tree.DecisionTreeClassifier()

In [79]:
model.fit(finputs,target)

DecisionTreeClassifier()

In [82]:
model.score(finputs,target)

0.9797979797979798

In [84]:
model.predict([[3,35,8,1]])

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)